[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

java.sourceCompatibility = 11
java.targetCompatibility = 11
if (JavaVersion.current().isJava9Compatible()) {
    compileJava.options.release.set(11)
}

eclipse.project.name = appName + '-client'

tasks.register("zipDlcCore", Zip) {
    from processDlcCoreResources.inputs.files
    archiveFileName = "dlc-core.qvcontent"
}

tasks.register("zipDlcExtended", Zip) {
    from processDlcExtendedResources.inputs.files
    archiveFileName = "dlc-extended.qvcontent"
}

afterEvaluate {

}

processResources {
    dependsOn("zipDlcCore", "zipDlcExtended")
    doFirst {
        copy {
            from zipDlcCore.outputs
            into rootProject.file("assets")
        }
        copy {
            from zipDlcExtended.outputs
            into rootProject.file("assets")
        }
    }
}

sourceSets {
    "dlc-core" {
        println(it.getClass())
        println(it.getClass().getInterfaces())
        println(it.getClass().getSuperclass())
        println(it.getClass().getSuperclass().getInterfaces())
        println(it.getClass().getSuperclass().getSuperclass())
    }

    "dlc-extended" {

    }
}

dependencies {
    api project(':common')

    api "com.badlogicgames.gdx:gdx:$gdxVersion"
    api "com.github.tommyettinger:regexodus:$regExodusVersion"
    api "com.github.tommyettinger:textratypist:$textratypistVersion"
    api "io.github.libktx:ktx-actors:$ktxVersion"
    api "io.github.libktx:ktx-ai:$ktxVersion"
    api "io.github.libktx:ktx-app:$ktxVersion"
    api "io.github.libktx:ktx-artemis:$ktxVersion"
    api "io.github.libktx:ktx-ashley:$ktxVersion"
    api "io.github.libktx:ktx-assets:$ktxVersion"
    api "io.github.libktx:ktx-collections:$ktxVersion"
    api "io.github.libktx:ktx-freetype:$ktxVersion"
    api "io.github.libktx:ktx-graphics:$ktxVersion"
    api "io.github.libktx:ktx-i18n:$ktxVersion"
    api "io.github.libktx:ktx-inject:$ktxVersion"
    api "io.github.libktx:ktx-json:$ktxVersion"
    api "io.github.libktx:ktx-log:$ktxVersion"
    api "io.github.libktx:ktx-math:$ktxVersion"
    api "io.github.libktx:ktx-preferences:$ktxVersion"
    api "io.github.libktx:ktx-reflect:$ktxVersion"
    api "io.github.libktx:ktx-scene2d:$ktxVersion"
    api "io.github.libktx:ktx-style:$ktxVersion"
    api "io.github.libktx:ktx-tiled:$ktxVersion"
    api "io.github.libktx:ktx-vis-style:$ktxVersion"
    api "io.github.libktx:ktx-vis:$ktxVersion"
    api "net.onedaybeard.artemis:artemis-odb:$artemisOdbVersion"
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
    api "space.earlygrey:shapedrawer:$shapeDrawerVersion"

    // Javet
    implementation 'com.caoccao.javet:javet:4.1.1'
    implementation 'com.caoccao.javet:javenode:0.8.0'

    // Guava
    implementation "com.google.guava:guava:33.4.0-jre"

    // FastUtils
    implementation "it.unimi.dsi:fastutil-core:8.5.15"

    // Kryo
    implementation "com.esotericsoftware:kryo:5.6.3-SNAPSHOT"
    implementation "com.esotericsoftware:kryonet:2.22.0-RC1"

    // GraalNative
    if (enableGraalNative == 'true') {
        implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
    }

    implementation "org.jetbrains.kotlin:kotlin-reflect:2.1.10"

    compileOnly "net.fabricmc:fabric-loader:$fabricLoaderVersion"
}
